SERVICE_NAME=go-api
INSECURE_MODE=true
OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317

run:
	@SERVICE_NAME=$(SERVICE_NAME) INSECURE_MODE=$(INSECURE_MODE) OTEL_EXPORTER_OTLP_ENDPOINT=$(OTEL_EXPORTER_OTLP_ENDPOINT) go run ./cmd/main.go